<?php
 
namespace App\Database\Seeds;
 
use CodeIgniter\Database\Seeder;
 
class EmployeeSeeder extends Seeder
{
    public function run()
    {
        // Truncate table first to avoid duplicates
        $this->db->query("TRUNCATE TABLE employees RESTART IDENTITY CASCADE");
 
        $employees = [
            [
                'nik' => '230045',
                'employee_name' => 'Budi Santoso',
                'position' => 'Operator',
                'section' => 'Cutting',
                'line' => 'A01',
                'skill_1' => 'Potong Backtab',
                'skill_1_grade' => 'A',
                'skill_2' => 'Potong Foam',
                'skill_2_grade' => 'B',
                'skill_3' => 'Potong Kulit',
                'skill_3_grade' => 'A',
                'skill_4' => 'Skiving',
                'skill_4_grade' => 'C',
                'skill_5' => 'Upper Preparation',
                'skill_5_grade' => 'B',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2023-01-15',
                'status' => 'Active'
            ],
            [
                'nik' => '230046',
                'employee_name' => 'Andi Wijaya',
                'position' => 'Operator',
                'section' => 'Sewing',
                'line' => 'A01',
                'skill_1' => 'Jahit Strobel',
                'skill_1_grade' => 'B',
                'skill_2' => 'Folding',
                'skill_2_grade' => 'B',
                'skill_3' => 'Trimming',
                'skill_3_grade' => 'A',
                'skill_4' => 'Jahit Side',
                'skill_4_grade' => 'C',
                'skill_5' => '',
                'skill_5_grade' => '',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2023-03-20',
                'status' => 'Active'
            ],
            [
                'nik' => '230047',
                'employee_name' => 'Siti Aminah',
                'position' => 'Operator',
                'section' => 'Assembly',
                'line' => 'A02',
                'skill_1' => 'Lasting Upper',
                'skill_1_grade' => 'A',
                'skill_2' => 'Sole Attaching',
                'skill_2_grade' => 'A',
                'skill_3' => 'Buffing',
                'skill_3_grade' => 'B',
                'skill_4' => 'Primer Application',
                'skill_4_grade' => 'B',
                'skill_5' => 'Cementing',
                'skill_5_grade' => 'A',
                'skill_6' => 'Clearing',
                'skill_6_grade' => 'C',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2022-11-10',
                'status' => 'Active'
            ],
            [
                'nik' => '230048',
                'employee_name' => 'Rian Hidayat',
                'position' => 'Pengawas',
                'section' => 'Sewing',
                'line' => 'A02',
                'skill_1' => 'Jahit Strobel',
                'skill_1_grade' => 'A',
                'skill_2' => 'Jahit Decorative',
                'skill_2_grade' => 'B',
                'skill_3' => 'Folding',
                'skill_3_grade' => 'B',
                'skill_4' => 'Trimming',
                'skill_4_grade' => 'A',
                'skill_5' => 'Quality Control',
                'skill_5_grade' => 'A',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2021-05-15',
                'status' => 'Active'
            ],
            [
                'nik' => '230049',
                'employee_name' => 'Dewi Lestari',
                'position' => 'Operator',
                'section' => 'Cutting',
                'line' => 'A03',
                'skill_1' => 'Potong Kulit',
                'skill_1_grade' => 'B',
                'skill_2' => 'Skiving',
                'skill_2_grade' => 'C',
                'skill_3' => 'Upper Preparation',
                'skill_3_grade' => 'B',
                'skill_4' => '',
                'skill_4_grade' => '',
                'skill_5' => '',
                'skill_5_grade' => '',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2023-06-01',
                'status' => 'Active'
            ],
            [
                'nik' => '230050',
                'employee_name' => 'Eko Prasetyo',
                'position' => 'Operator',
                'section' => 'Assembly',
                'line' => 'A04',
                'skill_1' => 'Sole Attaching',
                'skill_1_grade' => 'A',
                'skill_2' => 'Buffing',
                'skill_2_grade' => 'A',
                'skill_3' => 'Cementing',
                'skill_3_grade' => 'B',
                'skill_4' => 'Sole Pressing',
                'skill_4_grade' => 'C',
                'skill_5' => '',
                'skill_5_grade' => '',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2022-08-24',
                'status' => 'Active'
            ],
            [
                'nik' => '230051',
                'employee_name' => 'Farhan Nugraha',
                'position' => 'Operator',
                'section' => 'Sewing',
                'line' => 'A05',
                'skill_1' => 'Jahit Strobel',
                'skill_1_grade' => 'B',
                'skill_2' => 'Trimming',
                'skill_2_grade' => 'A',
                'skill_3' => 'Folding',
                'skill_3_grade' => 'B',
                'skill_4' => '',
                'skill_4_grade' => '',
                'skill_5' => '',
                'skill_5_grade' => '',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2023-09-12',
                'status' => 'Active'
            ],
            [
                'nik' => '230052',
                'employee_name' => 'Gita Permata',
                'position' => 'Operator',
                'section' => 'Cutting',
                'line' => 'A06',
                'skill_1' => 'Potong Backtab',
                'skill_1_grade' => 'A',
                'skill_2' => 'Potong Foam',
                'skill_2_grade' => 'C',
                'skill_3' => 'Upper Preparation',
                'skill_3_grade' => 'B',
                'skill_4' => '',
                'skill_4_grade' => '',
                'skill_5' => '',
                'skill_5_grade' => '',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2024-02-10',
                'status' => 'Active'
            ],
            [
                'nik' => '230053',
                'employee_name' => 'Hendra Wijaya',
                'position' => 'Operator',
                'section' => 'Assembly',
                'line' => 'A07',
                'skill_1' => 'Lasting Upper',
                'skill_1_grade' => 'A',
                'skill_2' => 'Cementing',
                'skill_2_grade' => 'B',
                'skill_3' => 'Sole Attaching',
                'skill_3_grade' => 'A',
                'skill_4' => 'Buffing',
                'skill_4_grade' => 'A',
                'skill_5' => 'Sole Pressing',
                'skill_5_grade' => 'C',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2023-04-05',
                'status' => 'Active'
            ],
            [
                'nik' => '230054',
                'employee_name' => 'Irma Suryani',
                'position' => 'Operator',
                'section' => 'Sewing',
                'line' => 'A08',
                'skill_1' => 'Jahit Strobel',
                'skill_1_grade' => 'B',
                'skill_2' => 'Folding',
                'skill_2_grade' => 'B',
                'skill_3' => 'Trimming',
                'skill_3_grade' => 'A',
                'skill_4' => '',
                'skill_4_grade' => '',
                'skill_5' => '',
                'skill_5_grade' => '',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2023-07-20',
                'status' => 'Inactive'
            ]
        ];
 
        foreach ($employees as $employee) {
            $this->db->table('employees')->insert($employee);
        }
    }
}
