<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class LeanEmployeeSeeder extends Seeder
{
    public function run()
    {
        // Truncate table first to avoid duplicates
        $this->db->query("TRUNCATE TABLE lean_employees RESTART IDENTITY CASCADE");

        $employees = [
            [
                'nik' => '990001',
                'employee_name' => 'Ferry Wijaya',
                'position' => 'Lean Manager',
                'section' => 'Continuous Improvement',
                'line' => 'Management',
                'skill_1' => 'Value Stream Mapping',
                'skill_1_grade' => 'A',
                'skill_2' => 'Kaizen Facilitation',
                'skill_2_grade' => 'A',
                'skill_3' => '5S & Visual Management',
                'skill_3_grade' => 'A',
                'skill_4' => 'Line Balancing',
                'skill_4_grade' => 'A',
                'skill_5' => 'Standardized Work',
                'skill_5_grade' => 'B',
                'skill_6' => '7 Wastes Identification',
                'skill_6_grade' => 'A',
                'skill_7' => 'Poka-Yoke',
                'skill_7_grade' => 'B',
                'skill_8' => 'SMED & Changeover',
                'skill_8_grade' => 'B',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2020-01-10',
                'status' => 'Active'
            ],
            [
                'nik' => '990002',
                'employee_name' => 'Zahra Amalia',
                'position' => 'CI Specialist',
                'section' => 'Continuous Improvement',
                'line' => 'Lean Office',
                'skill_1' => 'Kaizen Facilitation',
                'skill_1_grade' => 'A',
                'skill_2' => '5S & Visual Management',
                'skill_2_grade' => 'A',
                'skill_3' => '7 Wastes Identification',
                'skill_3_grade' => 'A',
                'skill_4' => 'Kanban & Pull Systems',
                'skill_4_grade' => 'B',
                'skill_5' => 'Value Stream Mapping',
                'skill_5_grade' => 'B',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2022-03-15',
                'status' => 'Active'
            ],
            [
                'nik' => '990003',
                'employee_name' => 'Bambang Sukojo',
                'position' => 'Lean Engineer',
                'section' => 'Continuous Improvement',
                'line' => 'Production Line',
                'skill_1' => 'SMED & Changeover',
                'skill_1_grade' => 'A',
                'skill_2' => 'Line Balancing',
                'skill_2_grade' => 'A',
                'skill_3' => '5S & Visual Management',
                'skill_3_grade' => 'B',
                'skill_4' => 'Poka-Yoke',
                'skill_4_grade' => 'B',
                'skill_5' => 'Standardized Work',
                'skill_5_grade' => 'A',
                'skill_6' => '7 Wastes Identification',
                'skill_6_grade' => 'B',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2021-08-20',
                'status' => 'Active'
            ],
            [
                'nik' => '990004',
                'employee_name' => 'Siska Handayani',
                'position' => 'IE Specialist',
                'section' => 'Industrial Engineering',
                'line' => 'Lean Office',
                'skill_1' => 'Line Balancing',
                'skill_1_grade' => 'A',
                'skill_2' => 'Standardized Work',
                'skill_2_grade' => 'A',
                'skill_3' => 'Value Stream Mapping',
                'skill_3_grade' => 'B',
                'skill_4' => '7 Wastes Identification',
                'skill_4_grade' => 'B',
                'skill_5' => '',
                'skill_5_grade' => '',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2023-05-12',
                'status' => 'Active'
            ],
            [
                'nik' => '990005',
                'employee_name' => 'Rahmat Hidayat',
                'position' => 'Lean Trainer',
                'section' => 'Training & Culture',
                'line' => 'Quality & Support',
                'skill_1' => '5S & Visual Management',
                'skill_1_grade' => 'A',
                'skill_2' => 'Kaizen Facilitation',
                'skill_2_grade' => 'B',
                'skill_3' => '7 Wastes Identification',
                'skill_3_grade' => 'A',
                'skill_4' => 'Standardized Work',
                'skill_4_grade' => 'B',
                'skill_5' => '',
                'skill_5_grade' => '',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2024-02-01',
                'status' => 'Active'
            ],
            [
                'nik' => '990006',
                'employee_name' => 'Dwi Kartika',
                'position' => 'CI Specialist',
                'section' => 'Continuous Improvement',
                'line' => 'Lean Office',
                'skill_1' => 'Value Stream Mapping',
                'skill_1_grade' => 'B',
                'skill_2' => 'Kaizen Facilitation',
                'skill_2_grade' => 'C',
                'skill_3' => '5S & Visual Management',
                'skill_3_grade' => 'A',
                'skill_4' => '',
                'skill_4_grade' => '',
                'skill_5' => '',
                'skill_5_grade' => '',
                'skill_6' => '',
                'skill_6_grade' => '',
                'skill_7' => '',
                'skill_7_grade' => '',
                'skill_8' => '',
                'skill_8_grade' => '',
                'skill_9' => '',
                'skill_9_grade' => '',
                'skill_10' => '',
                'skill_10_grade' => '',
                'join_date' => '2023-11-15',
                'status' => 'Inactive'
            ]
        ];

        foreach ($employees as $employee) {
            $this->db->table('lean_employees')->insert($employee);
        }
    }
}
